// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageType int32

const (
	MessageType_NONE  MessageType = 0
	MessageType_P2P   MessageType = 1
	MessageType_GROUP MessageType = 2
)

var MessageType_name = map[int32]string{
	0: "NONE",
	1: "P2P",
	2: "GROUP",
}

var MessageType_value = map[string]int32{
	"NONE":  0,
	"P2P":   1,
	"GROUP": 2,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}

func (MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

type MessageResponse_Status int32

const (
	MessageResponse_Ok        MessageResponse_Status = 0
	MessageResponse_NotRouted MessageResponse_Status = 1
)

var MessageResponse_Status_name = map[int32]string{
	0: "Ok",
	1: "NotRouted",
}

var MessageResponse_Status_value = map[string]int32{
	"Ok":        0,
	"NotRouted": 1,
}

func (x MessageResponse_Status) String() string {
	return proto.EnumName(MessageResponse_Status_name, int32(x))
}

func (MessageResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1, 0}
}

type WsResponse_Status int32

const (
	WsResponse_NONE  WsResponse_Status = 0
	WsResponse_Ok    WsResponse_Status = 1
	WsResponse_Error WsResponse_Status = 2
)

var WsResponse_Status_name = map[int32]string{
	0: "NONE",
	1: "Ok",
	2: "Error",
}

var WsResponse_Status_value = map[string]int32{
	"NONE":  0,
	"Ok":    1,
	"Error": 2,
}

func (x WsResponse_Status) String() string {
	return proto.EnumName(WsResponse_Status_name, int32(x))
}

func (WsResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2, 0}
}

type MessageRequest struct {
	TargetIds            []string          `protobuf:"bytes,1,rep,name=targetIds,proto3" json:"targetIds,omitempty"`
	Message              *WsMessageRequest `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MessageRequest) Reset()         { *m = MessageRequest{} }
func (m *MessageRequest) String() string { return proto.CompactTextString(m) }
func (*MessageRequest) ProtoMessage()    {}
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *MessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRequest.Unmarshal(m, b)
}
func (m *MessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRequest.Marshal(b, m, deterministic)
}
func (m *MessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRequest.Merge(m, src)
}
func (m *MessageRequest) XXX_Size() int {
	return xxx_messageInfo_MessageRequest.Size(m)
}
func (m *MessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRequest proto.InternalMessageInfo

func (m *MessageRequest) GetTargetIds() []string {
	if m != nil {
		return m.TargetIds
	}
	return nil
}

func (m *MessageRequest) GetMessage() *WsMessageRequest {
	if m != nil {
		return m.Message
	}
	return nil
}

type MessageResponse struct {
	Status               MessageResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=proto.MessageResponse_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *MessageResponse) Reset()         { *m = MessageResponse{} }
func (m *MessageResponse) String() string { return proto.CompactTextString(m) }
func (*MessageResponse) ProtoMessage()    {}
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *MessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageResponse.Unmarshal(m, b)
}
func (m *MessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageResponse.Marshal(b, m, deterministic)
}
func (m *MessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageResponse.Merge(m, src)
}
func (m *MessageResponse) XXX_Size() int {
	return xxx_messageInfo_MessageResponse.Size(m)
}
func (m *MessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageResponse proto.InternalMessageInfo

func (m *MessageResponse) GetStatus() MessageResponse_Status {
	if m != nil {
		return m.Status
	}
	return MessageResponse_Ok
}

type WsResponse struct {
	Status               WsResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=proto.WsResponse_Status" json:"status,omitempty"`
	Message              string            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *WsResponse) Reset()         { *m = WsResponse{} }
func (m *WsResponse) String() string { return proto.CompactTextString(m) }
func (*WsResponse) ProtoMessage()    {}
func (*WsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *WsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WsResponse.Unmarshal(m, b)
}
func (m *WsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WsResponse.Marshal(b, m, deterministic)
}
func (m *WsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WsResponse.Merge(m, src)
}
func (m *WsResponse) XXX_Size() int {
	return xxx_messageInfo_WsResponse.Size(m)
}
func (m *WsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WsResponse proto.InternalMessageInfo

func (m *WsResponse) GetStatus() WsResponse_Status {
	if m != nil {
		return m.Status
	}
	return WsResponse_NONE
}

func (m *WsResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type WsHandshakeRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Secret               string   `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WsHandshakeRequest) Reset()         { *m = WsHandshakeRequest{} }
func (m *WsHandshakeRequest) String() string { return proto.CompactTextString(m) }
func (*WsHandshakeRequest) ProtoMessage()    {}
func (*WsHandshakeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *WsHandshakeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WsHandshakeRequest.Unmarshal(m, b)
}
func (m *WsHandshakeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WsHandshakeRequest.Marshal(b, m, deterministic)
}
func (m *WsHandshakeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WsHandshakeRequest.Merge(m, src)
}
func (m *WsHandshakeRequest) XXX_Size() int {
	return xxx_messageInfo_WsHandshakeRequest.Size(m)
}
func (m *WsHandshakeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WsHandshakeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WsHandshakeRequest proto.InternalMessageInfo

func (m *WsHandshakeRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *WsHandshakeRequest) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

type WsMessageRequest struct {
	MessageId            string      `protobuf:"bytes,1,opt,name=messageId,proto3" json:"messageId,omitempty"`
	TargetId             string      `protobuf:"bytes,2,opt,name=targetId,proto3" json:"targetId,omitempty"`
	Type                 MessageType `protobuf:"varint,3,opt,name=type,proto3,enum=proto.MessageType" json:"type,omitempty"`
	Data                 string      `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	SourceId             string      `protobuf:"bytes,5,opt,name=sourceId,proto3" json:"sourceId,omitempty"`
	Ext                  int32       `protobuf:"varint,6,opt,name=ext,proto3" json:"ext,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *WsMessageRequest) Reset()         { *m = WsMessageRequest{} }
func (m *WsMessageRequest) String() string { return proto.CompactTextString(m) }
func (*WsMessageRequest) ProtoMessage()    {}
func (*WsMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *WsMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WsMessageRequest.Unmarshal(m, b)
}
func (m *WsMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WsMessageRequest.Marshal(b, m, deterministic)
}
func (m *WsMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WsMessageRequest.Merge(m, src)
}
func (m *WsMessageRequest) XXX_Size() int {
	return xxx_messageInfo_WsMessageRequest.Size(m)
}
func (m *WsMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WsMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WsMessageRequest proto.InternalMessageInfo

func (m *WsMessageRequest) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *WsMessageRequest) GetTargetId() string {
	if m != nil {
		return m.TargetId
	}
	return ""
}

func (m *WsMessageRequest) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_NONE
}

func (m *WsMessageRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *WsMessageRequest) GetSourceId() string {
	if m != nil {
		return m.SourceId
	}
	return ""
}

func (m *WsMessageRequest) GetExt() int32 {
	if m != nil {
		return m.Ext
	}
	return 0
}

func init() {
	proto.RegisterEnum("proto.MessageType", MessageType_name, MessageType_value)
	proto.RegisterEnum("proto.MessageResponse_Status", MessageResponse_Status_name, MessageResponse_Status_value)
	proto.RegisterEnum("proto.WsResponse_Status", WsResponse_Status_name, WsResponse_Status_value)
	proto.RegisterType((*MessageRequest)(nil), "proto.MessageRequest")
	proto.RegisterType((*MessageResponse)(nil), "proto.MessageResponse")
	proto.RegisterType((*WsResponse)(nil), "proto.WsResponse")
	proto.RegisterType((*WsHandshakeRequest)(nil), "proto.WsHandshakeRequest")
	proto.RegisterType((*WsMessageRequest)(nil), "proto.WsMessageRequest")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 363 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x4d, 0x4b, 0xfb, 0x40,
	0x10, 0xc6, 0x9b, 0xd7, 0x36, 0x53, 0xda, 0x7f, 0x98, 0xc3, 0xdf, 0x20, 0x8a, 0x25, 0xa0, 0x04,
	0x85, 0xa2, 0x15, 0x6f, 0x5e, 0x8b, 0xf6, 0x60, 0x5b, 0x56, 0xa5, 0xe7, 0xb5, 0x59, 0x6a, 0x29,
	0x76, 0xe3, 0xee, 0x06, 0xec, 0xc9, 0x6f, 0xe5, 0xe7, 0x93, 0x6c, 0x36, 0xe9, 0x0b, 0x78, 0xca,
	0xce, 0xec, 0xe4, 0xf7, 0x3c, 0xf3, 0x2c, 0x74, 0x3e, 0x98, 0x94, 0x74, 0xc1, 0xfa, 0x99, 0xe0,
	0x8a, 0xa3, 0xa7, 0x3f, 0x31, 0x85, 0xee, 0x53, 0xd9, 0x27, 0xec, 0x33, 0x67, 0x52, 0xe1, 0x09,
	0x04, 0x8a, 0x8a, 0x05, 0x53, 0xa3, 0x54, 0x46, 0x56, 0xcf, 0x49, 0x02, 0xb2, 0x6d, 0xe0, 0x0d,
	0x34, 0x0d, 0x27, 0xb2, 0x7b, 0x56, 0xd2, 0x1e, 0x1c, 0x95, 0xbc, 0xfe, 0x4c, 0xee, 0x73, 0x48,
	0x35, 0x17, 0x2f, 0xe1, 0x5f, 0x7d, 0x25, 0x33, 0xbe, 0x96, 0x0c, 0xef, 0xc0, 0x97, 0x8a, 0xaa,
	0xbc, 0x10, 0xb0, 0x92, 0xee, 0xe0, 0xd4, 0x40, 0x0e, 0xe6, 0xfa, 0xcf, 0x7a, 0x88, 0x98, 0xe1,
	0xf8, 0x0c, 0xfc, 0xb2, 0x83, 0x3e, 0xd8, 0x93, 0x55, 0xd8, 0xc0, 0x0e, 0x04, 0x63, 0xae, 0x08,
	0xcf, 0x15, 0x4b, 0x43, 0x2b, 0xfe, 0x06, 0x98, 0xc9, 0x5a, 0xe5, 0xfa, 0x40, 0x25, 0xaa, 0xad,
	0xfe, 0x21, 0x80, 0xd1, 0xfe, 0x76, 0xc1, 0x76, 0x89, 0xf3, 0x5a, 0xba, 0x05, 0xee, 0x78, 0x32,
	0x1e, 0x86, 0x0d, 0x63, 0xc2, 0xc2, 0x00, 0xbc, 0xa1, 0x10, 0x5c, 0x84, 0x76, 0x7c, 0x0f, 0x38,
	0x93, 0x8f, 0x74, 0x9d, 0xca, 0x77, 0xba, 0xaa, 0x23, 0xed, 0x82, 0xbd, 0x4c, 0xb5, 0x89, 0x80,
	0xd8, 0xcb, 0x14, 0xff, 0x83, 0x2f, 0xd9, 0x5c, 0x30, 0x65, 0x54, 0x4c, 0x15, 0xff, 0x58, 0x10,
	0x1e, 0xe6, 0x58, 0xbc, 0x87, 0x31, 0x31, 0xaa, 0x18, 0xdb, 0x06, 0x1e, 0x43, 0xab, 0x7a, 0x1c,
	0x03, 0xab, 0x6b, 0xbc, 0x00, 0x57, 0x6d, 0x32, 0x16, 0x39, 0x7a, 0x7b, 0xdc, 0xcf, 0xf8, 0x65,
	0x93, 0x31, 0xa2, 0xef, 0x11, 0xc1, 0x4d, 0xa9, 0xa2, 0x91, 0xab, 0xff, 0xd7, 0xe7, 0x82, 0x2b,
	0x79, 0x2e, 0xe6, 0x85, 0xa8, 0x57, 0x72, 0xab, 0x1a, 0x43, 0x70, 0xd8, 0x97, 0x8a, 0xfc, 0x9e,
	0x95, 0x78, 0xa4, 0x38, 0x5e, 0x5e, 0x41, 0x7b, 0x07, 0xbb, 0x13, 0x51, 0x13, 0x9c, 0xe9, 0x60,
	0x5a, 0x66, 0xf4, 0x40, 0x26, 0xaf, 0xd3, 0xd0, 0x7e, 0xf3, 0xb5, 0x8f, 0xdb, 0xdf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xf4, 0x4a, 0x83, 0xaa, 0x91, 0x02, 0x00, 0x00,
}
